import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

interface RootLayoutProps {
    children: React.ReactNode;
    params: {
        locale: string;
    };
}

export default async function RootLayout({
    children,
    params: { locale }
}: Readonly<RootLayoutProps>) {
    const messages = await getMessages();
    return (
        <html lang={locale}>
            <body className={inter.className}>
                <NextIntlClientProvider messages={messages}>
                    <div className="flex flex-col min-h-screen max-w-4xl mx-auto">
                        <div className="flex items-center justify-center mt-20">
                            {children}
                        </div>
                    </div>
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
